# Generated by Django 4.1.4 on 2022-12-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text_order', models.PositiveSmallIntegerField(default=1)),
                ('collection', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('languages', models.CharField(blank=True, max_length=100)),
                ('number_chapters', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'text',
                'verbose_name_plural': 'texts',
                'ordering': ('text_id',),
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence_inner_id', models.CharField(blank=True, max_length=64, null=True)),
                ('chapter_name', models.CharField(blank=True, max_length=300, null=True)),
                ('chapter_number', models.PositiveSmallIntegerField(default=1)),
                ('en', models.TextField(blank=True, null=True)),
                ('es', models.TextField(blank=True, null=True)),
                ('pt', models.TextField(blank=True, null=True)),
                ('fr', models.TextField(blank=True, null=True)),
                ('it', models.TextField(blank=True, null=True)),
                ('de', models.TextField(blank=True, null=True)),
                ('ro', models.TextField(blank=True, null=True)),
                ('hu', models.TextField(blank=True, null=True)),
                ('nl', models.TextField(blank=True, null=True)),
                ('da', models.TextField(blank=True, null=True)),
                ('id', models.TextField(blank=True, null=True)),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='readerapp.text')),
            ],
            options={
                'ordering': ('id',),
                'index_together': {('id', 'text_id')},
            },
        ),
    ]
